#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Estimotes.Droid.Resource", IsApplication=true)]

namespace Estimotes.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int disappear = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int grow_from_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int grow_from_bottomleft_to_topright = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int grow_from_bottomright_to_topleft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int grow_from_top = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int grow_from_topleft_to_bottomright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int grow_from_topright_to_bottomleft = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int pump_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int pump_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int rail = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int shrink_from_bottom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int shrink_from_bottomleft_to_topright = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int shrink_from_bottomright_to_topleft = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int shrink_from_top = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int shrink_from_topleft_to_bottomright = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int shrink_from_topright_to_bottomleft = 2130968591;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_item_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_item_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int beacon_blueberry = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int beacon_gray = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int beacon_icy = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_distance = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dot = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_refresh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int popup = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int arrow_down = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int arrow_up = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int device_list = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int dot = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int iv_icon = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int refresh = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int root = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int scroller = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int sonar = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int status = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int stop = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int tracks = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int tv_title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_item_horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int action_item_vertical = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int actionbar_indeterminate_progress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int device_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int distance_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int horiz_separator = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notify_demo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int popup_horizontal = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int popup_vertical = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int scan_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Animations = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Animations_PopDownMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Animations_PopDownMenu_Center = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Animations_PopDownMenu_Left = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Animations_PopDownMenu_Reflect = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int Animations_PopDownMenu_Right = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Animations_PopUpMenu = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Animations_PopUpMenu_Center = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Animations_PopUpMenu_Left = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int Animations_PopUpMenu_Reflect = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int Animations_PopUpMenu_Right = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
